---
jobs:

- name: set-self
  plan:
    - get: cf-service-connect-repo
      trigger: true
    - set_pipeline: self
      file: cf-service-connect-repo/ci/pipeline.yml

- name: run-tests
  plan:
    - get: cf-service-connect-repo
      passed: [set-self]
      trigger: true
    - task: run-tests
      file: cf-service-connect-repo/ci/run-tests.yml

- name: create-release
  plan:
    - get: cf-service-connect-repo
      passed: [run-tests]
      trigger: true
    - task: release
      file: cf-service-connect-repo/ci/create-release.yml
  on_failure:
    put: slack
    params:
        text: |
            :x: FAILED to release cf-service-connect-repo
            <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: ((slack-failure-channel))
        username: ((slack-username))
        icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
        text: |
            :white_check_mark: Successfully released cf-service-connect-repo
            <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: ((slack-success-channel))
        username: ((slack-username))
        icon_url: ((slack-icon-url))

resources:
# this resource is this repo
# NOTE: we only execute on tag changes not commits, see tag_regex
- name: cf-service-connect-repo
  type: git
  source:
    uri: https://github.com/cloud-gov/cf-service-connect.git
    branch: allow-cf-binary-name-override
    # private_key: ((cg-ci-bot-sshkey.private_key))
    # only run on new tags matching pattern like: v0.1.5
    # tag_regex: '^v([0-9]+\.){0,2}(\*|[0-9]+)$'
    commit_verification_keys: ((cloud-gov-pgp-keys))

# This resource for posting to slack
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
